language: java
jdk:
  - openjdk8
dist: bionic
env:
  - CCM_CLUSTER_START_TIMEOUT_OVERRIDE=600
#  - DB=mongodb SUITE=all
#  - DB=mongodb SUITE=compact
#  - DB=redis
#  - DB=mysql
before_install:
  - git clone --branch master --single-branch https://github.com/riptano/ccm.git
  - pushd ccm || exit
  - sudo python setup.py install
  - popd
install: mvn install --settings ci/mvn-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
script: ci/test.sh
cache:
  directories:
    - $HOME/.m2
