language: java
jdk:
  - openjdk8
dist: bionic
env:
  - CCM_CLUSTER_START_TIMEOUT_OVERRIDE=600
#  - DB=mongodb SUITE=all
#  - DB=mongodb SUITE=compact
#  - DB=redis
#  - DB=mysql
before_install:
  # Require JDK8 for compiling
  - jdk_switcher use openjdk8
  - git clone --branch master --single-branch https://github.com/riptano/ccm.git
  - pushd ccm || exit
  - sudo python setup.py install
  - popd
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -B verify --file pom.xml -P it-cassandra-3.11 -P it-cassandra-4.0 -P !it-dse-6.8
cache:
  directories:
    - $HOME/.m2
